# This is a basic workflow to help you get started with Actions

name: get json file

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: 
    - main
  schedule:
    - cron:  '0 */4 * * *'  #every 4

jobs:
  keep_file_updated:
    runs-on: ubuntu-latest
    name: Keep file updated
    steps:
    - uses: actions/checkout@v2
    - name: Update file
      id: update_file
      uses: mark2me/covid19-tw@main
      with:
        url: https://od.cdc.gov.tw/eic/Day_Confirmation_Age_County_Gender_19CoV.json
        file_in_repo: Day_Confirmation_Age_County_Gender_19CoV.json
        
