# This is a basic workflow to help you get started with Actions

name: get json file

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  schedule:
    - cron:  '0 */4 * * *'  #every 4
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    branches: [ main ]
        
jobs:
  wget:
    runs-on: ubuntu-latest
    steps:
    - name: wget
      uses: mark2me/covid19-tw@main
      with:
        args: -O sample.json https://data.cdc.gov.tw/download?resourceid=a59483fd-4b09-42bd-af15-3c123147d7e3&dataurl=https://od.cdc.gov.tw/eic/Day_Confirmation_Age_County_Gender_19CoV.json
